### ISSUE TITLE
Issue tracker is hard to find

### ISSUE THREAD

**Issue by tgr** [hartman/toolforge-deployscript-zonestamp#2]
I found it eventually via https://admin.toolforge.org/tool/zonestamp (which, for some reason, has two info entries...) but a link from https://zonestamp.toolforge.org/ itself would be nice.

**Comment by lucaswerkmeister** [comment]
Apparently there is also https://github.com/hartman/zonestamp, with a second set of issues, so yeah, I think it’s fair to say that it’s not exactly easy to find “the” issue tracker…

(For the record, I also found this one via tooladmin.)

**Comment by trnstlntk** [comment]
Haha, I also arrived here after diligently searching (I arrived here via Toolhub). It would be good to display a canonical link for anyone using Zonestamp itself.
