### ISSUE TITLE
DST incorrectly applied (upstream is fixed)

### ISSUE THREAD

**Issue by Krinkle** [hartman/toolforge-deployscript-zonestamp#3]
Example date: 14:00 UTC, 29 June 2021.

Toolforge install: <https://zonestamp.toolforge.org/1624975200>.
<img width="702" alt="Screenshot 2021-06-21 at 04 29 55" src="https://user-images.githubusercontent.com/156867/122703392-5bd40800-d249-11eb-8e83-54ce40ecf50a.png">

Upstream install: <https://zonestamp.com/1624975200>.

The Toolforge install (correctly) tells me that it will be **3:00 pm** here (I'm in the UK, and we're on +01:00 BST currently). But it then says below that that it is displaying "GMT+00:00 United Kingdom", which is incorrect.

This is especially confusing when creating links for other people, because when I'm creating a link for 14:00 GMT+00:00, I'm actually creating a link for 15:00 UTC, instead of 14:00 UTC, which even when previewing I would not know is off by one hour.

I don't see commits upstream after this fork started, so I'm guessing this might be an issue with dependencies or configuration?

**Comment by lucaswerkmeister** [comment]
It looks like this was fixed, somehow, in https://phabricator.wikimedia.org/T252373. (Though the only new commit on master, eb1252d8069c708d178dfdfa637b7702c440dd2d, doesn’t look very related to me.)

**Comment by hartman** [comment]
Closed
