### ISSUE TITLE
'Add to my calendar' link

### ISSUE THREAD

**Issue by trnstlntk** [hartman/toolforge-deployscript-zonestamp#5]
When I check Zonestamp, it is usually to verify if a planned Wikimedia event fits into my agenda.

It would be super handy if there would be a link that allows me to immediately create an appointment in my personal calendar :-)

I am an evil and unethical user of Google Calendar and I would love a link to immediately create a Gcal event. For users of less contested services an .ics link would also be great, I think. I'm not specialized in calendar stuff at all, so I have no other suggestions so far, but I can imagine this can be made more user friendly in various ways.

Many thanks to the maintainers of this handy tool, I love it! :-)

**Comment by olea** [comment]
I can't agree more :)

**Comment by pigsonthewing** [comment]
Please, please do this!

**Comment by hartman** [comment]
Wrong repo, but now implemented in hartman/zonestamp#6
