### ISSUE TITLE
Make 24/12 hour clock switch sticky

### ISSUE THREAD

**Issue by VDK** [hartman/toolforge-deployscript-zonestamp#6]
Could the switch from a 12 to a 24 hour clock please be made sticky?
This would probably require a cookie. This would work similar as the language settings cookie that is given as an example of the kind of cookie that doesn't require permission in [this guide on the gdpr](https://www.iubenda.com/en/help/5525-cookies-gdpr-requirements).

**Comment by hartman** [comment]
hartman/zonestamp#21
